name: 🧹 Clean Artifacts
on:
  workflow_run:
    workflows: ["Deployment"]
    types: [completed]

jobs:
  cleanup:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: '*'
          token: ${{ secrets.GITHUB_TOKEN }}
