# .github/workflows/cleanup-artifacts.yml
name: 🧹 Clean up webapp artifacts

on:
  workflow_run:
    workflows: ["Build and deploy .NET Core application to Web App MyAppAzureTest"]
    types: [completed]

permissions:
  actions: write   # grant the GITHUB_TOKEN permission to delete artifacts

jobs:
  cleanup:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Delete all “webapp” artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: webapp
